elasticsearch service is restarted if it fails on error
shopsys/demoshop pull request #23
Opened 2018-10-16 10:00 UTC by boris-brtan

restart parameter for elasticsearch service was added into docker-compose.yml.dist configuration files

| Q             | A
| ------------- | ---
|Description, reason for the PR| sometimes when multiple instances of demoshop run on the ci server elasticsearch container fails on error 137 and it needs to be restarted so searching microservices start to work again
|New feature| No 
|BC breaks| No 
|Fixes issues| #21
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2018-10-17 15:15 UTC, MattCzerner requested changes
Hey :)
I dont think that restarting the container solves the problem, after few google searches I found out that it is because of not enough memory. My opinion is that it should be fixed on server side, not by a code, does this really solves anything and can i replicate it on my local?

Issue about error 137:
https://github.com/moby/moby/issues/21083

Docker documentation about memory:
https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

I am not sure about this though. Can you describe how to replicate error? Or is this even happening on local?

2018-10-22 14:57 UTC, boris-brtan commented
replication of the error could be done via kill command.
but this is happening when there are more instances running and they exhaust resource limits.
Now there was an idea to do it for all containers. can you @MattCzerner  please do some CR?

2018-10-23 06:45 UTC, boris-brtan commented
But we decided solve this as a Hotfix for the scope of the BUG, so can you do CR again? THX

2018-10-23 14:15 UTC, MattCzerner approved these changes

2018-10-24 12:10 UTC, merged