Upgrade demoshop to beta2 version
shopsys/demoshop pull request #26
Opened 2018-10-30 11:31 UTC by MattCzerner

| Q             | A
| ------------- | ---
|Description, reason for the PR| Keep demoshop upgraded with newest version of Framework
|New feature| No
|BC breaks| No
|Fixes issues| 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2018-10-31 13:26 UTC, Miroslav-Stopka requested changes
Hi @MattCzerner,
I have only a few questions, please check them.

Seems like this upgrade was easy thanks to detailed UPGRADE.md. What do you think?

2018-10-31 13:26 UTC, Miroslav-Stopka commented on docker/php-fpm/Dockerfile
>  ARG www_data_uid
Question, what about docker/php-fpm/production/Dockerfile?

Will be the application still functional in production if you dont modify Dockerfile for production?

2018-10-31 13:26 UTC, Miroslav-Stopka commented on composer.json
> -        }
Wait, why composer.json is modified in this commit?

2018-10-31 13:26 UTC, Miroslav-Stopka commented on composer.json
> +        "shopsys/doctrine-orm": "2.6.2",
I dont see any connection of this compose.json modification with the microservices??

2018-10-31 13:26 UTC, Miroslav-Stopka commented on app/config/parameters.yml.dist
seems strange, but the original PR https://github.com/shopsys/shopsys/pull/494/files contains also the modifications of project-base/kubernetes/... Did you processed these modifications too?

2018-10-31 13:26 UTC, Miroslav-Stopka commented on composer.json
> +        "symfony/dependency-injection": "3.4.15|3.4.16"
Just asking, was this modification necessary? I think it was. Am I right? If so, this modification should not be marked as optional in our UPGRADE.md. Actually, I'm probably against this mark optional in our UPGRADE.md. What do you think?

2018-10-31 13:26 UTC, Miroslav-Stopka commented on build-dev.xml
> +    <target name="test-db-demo" depends="clean,test-db-wipe-public-schema,test-db-import-basic-structure,test-db-migrations,test-create-domains-db-functions,test-db-fixtures-demo-singledomain,test-cr
Interesting, this `clean` target was not added as a dependency for `test-db-demo` while the domains phing targets modifications. Seems like PH does not updated UPGRADE.md in the past. But I think that you did a better job when you fixed it. +1

2018-11-08 08:41 UTC, MattCzerner commented on docker/php-fpm/Dockerfile
>  ARG www_data_uid
php.ini overrides is already added during build of production dockerfile

2018-11-08 08:44 UTC, MattCzerner commented on composer.json
> -        }
Oh, yeah wrong commit. I wonder if these commits should be squashed all together at the end. If not I will rebase it before merging and fix this :)

2018-11-08 08:45 UTC, MattCzerner commented on composer.json
> +        "shopsys/doctrine-orm": "2.6.2",
I answered you in previous comment :)

2018-11-08 08:46 UTC, MattCzerner commented on app/config/parameters.yml.dist
No, because demoshop does not contains kubernetes manifests at this moment. This was discussed with @PetrHeinz that it will be added in the future.

2018-11-08 08:48 UTC, MattCzerner commented on composer.json
> +        "symfony/dependency-injection": "3.4.15|3.4.16"
Well I dont know actually, the instruction in UPGRADE.md does not contain information about why should i do it. But i guess that if these version make application broken than it should not be optional for sure. Should I write some feedback to a person who wrote it into UPGRADE?

2018-11-08 08:50 UTC, MattCzerner commented
Please review my comments and if it will be all right with you. We can discuss if we should merge all commits as one and if not i will perform rebase where I will make single commit for fork deletion.

2018-11-08 11:20 UTC, Miroslav-Stopka commented on composer.json
> +        "symfony/dependency-injection": "3.4.15|3.4.16"
I suggest to stop using "optional" permanently, but this decission is not on me.

2018-11-08 11:22 UTC, Miroslav-Stopka commented
CR is done. You should process the rebase right now and the final version should be tested.

2018-11-08 11:22 UTC, Miroslav-Stopka approved these changes

2018-11-12 11:48 UTC, boris-brtan requested changes
as for the last commit, there exists [this PR](https://github.com/shopsys/demoshop/pull/22/files) so there are also fixes for postgres version from 9.5 to 10 so please decide if you cherry pick these changes or resolve this PR first and then we do merge of this one because this last commit is incomplete
and also docker-sync for windows is not here but that change is highly optional but it is not absolutely in `UPGRADE.md`

2018-11-12 11:59 UTC, boris-brtan commented
i would suggest to do it without tha change of -win and -mac confs and after that update CR TEST and MERGE @Miroslav-Stopka  PR

2018-11-13 18:59 UTC, MattCzerner commented
Changes of @Miroslav-Stopka can be merged after this is finished. Actually it wont be even problem to rebase on it. 

Currently we got 2 not functional docker configurations in repository and we suggest to use them. I suggest to merge this PR as it is, make application functional and then solve the PR of #22

2018-11-14 06:50 UTC, boris-brtan commented
This way is also OK, so not forget to mention this thing remaining thing.

2018-11-14 06:50 UTC, boris-brtan approved these changes

2018-11-14 06:55 UTC, boris-brtan commented
TESTS:
production - OK
CI - OK
local development - OK

2018-11-14 13:31 UTC, merged