discount for customer
shopsys/demoshop pull request #31
Opened 2019-01-09 06:45 UTC by boris-brtan

- administration of customer now contains discount field with range validation that is reflected into User entity
- prices of products are recalculated for logged customers based on custom discount
- discount works also for companies with multiple users

| Q             | A
| ------------- | ---
|Description, reason for the PR| we want to test the extensibility of pricing from Shopsys Framework
|New feature| Yes 
|BC breaks| No 
|Fixes issues| -
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-01-09 06:48 UTC, boris-brtan commented on src/Shopsys/ShopBundle/Resources/translations/validators.en.po
> -
hmm this was strange

2019-01-09 12:59 UTC, DavidOstrozlik requested changes
I reviewed this PR and found just 2 cosmetic changes.
Tests: I found that:
- you can't save User if you didn't fill the discount - fixed
- on Firefox you can fill discount with letters and it doesn't show the correct invalid message - problem for mozilla i will create issue https://github.com/shopsys/shopsys/issues/717
- on Firefox the JS validation of discount doesn't work - problem for mozilla i will create issue

2019-01-09 12:59 UTC, DavidOstrozlik commented on CHANGELOG.md
> +- [#31 - discount for customer](https://github.com/shopsys/demoshop/pull/31)
It's just a cosmetic issue. I also changed title of this PR.

```suggestion
- [#31 - Discount for customer](https://github.com/shopsys/demoshop/pull/31)
```

2019-01-09 12:59 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/translations/validators.cs.po
> +msgstr "Procentní Sleva musí být validní čísovka s rozmezím mezi 0 a 100"
```suggestion
msgstr "Procentní sleva musí být celé číslo v rozmezí 0 až 100"
```

2019-01-09 15:15 UTC, boris-brtan commented
Hi, i did the fixes and created issue for the JSFormValidator for mozilla browsers

2019-01-10 07:45 UTC, boris-brtan commented
I see the same thing as in promocode so i put 0 as default value and put there not blank constraints

2019-01-10 10:25 UTC, boris-brtan commented
now there is need to test also filtering by price

2019-01-10 15:18 UTC, DavidOstrozlik requested changes

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/User.php
> +     * @var int|null
```suggestion
     * @var int
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/User.php
> +     * @return int|null
```suggestion
     * @return int
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/User.php
> +    public function getDiscount(): ?int
```suggestion
    public function getDiscount(): int
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/UserData.php
> +     * @var int|null
```suggestion
     * @var int
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/CurrentCustomer.php
> +            return null;
```suggestion
            return 0;
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Customer/CurrentCustomer.php
> +     * @return int|null
```suggestion
     * @return int
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +     * @param int|null $customDiscount
```suggestion
     * @param int $customDiscount
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +    public function calculatePrice(Product $product, $domainId, PricingGroup $pricingGroup, $customDiscount = null)
```suggestion
    public function calculatePrice(Product $product, $domainId, PricingGroup $pricingGroup, $customDiscount)
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +     * @param int|null $customDiscount
```suggestion
     * @param int $customDiscount
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +    private function calculateMainVariantPrice(Product $mainVariant, $domainId, PricingGroup $pricingGroup, $customDiscount = null)
```suggestion
    private function calculateMainVariantPrice(Product $mainVariant, $domainId, PricingGroup $pricingGroup, $customDiscount)
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +     * @param int|null $customDiscount
```suggestion
     * @param int $customDiscount
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +    private function calculateProductPriceForPricingGroup(Product $product, PricingGroup $pricingGroup, $customDiscount = null)
```suggestion
    private function calculateProductPriceForPricingGroup(Product $product, PricingGroup $pricingGroup, $customDiscount)
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +            $inputPrice = $manualInputPrice->getInputPrice() * (100 - $customDiscount ?? 100) / 100;
```suggestion
            $inputPrice = $manualInputPrice->getInputPrice() * (100 - $customDiscount) / 100;
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculationForUser.php
> +     * @var \Shopsys\FrameworkBundle\Model\Customer\CurrentCustomer
```suggestion
     * @var \Shopsys\ShopBundle\Model\Customer\CurrentCustomer
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculationForUser.php
> +use Shopsys\FrameworkBundle\Model\Customer\CurrentCustomer;
```suggestion
use Shopsys\ShopBundle\Model\Customer\CurrentCustomer;
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculationForUser.php
> +     * @param \Shopsys\FrameworkBundle\Model\Customer\CurrentCustomer $currentCustomer
```suggestion
     * @param \Shopsys\ShopBundle\Model\Customer\CurrentCustomer $currentCustomer
```

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculation.php
> +use Shopsys\FrameworkBundle\Model\Pricing\BasePriceCalculation;
Please change `FrameworkBundle` to `ShopBundle` in usages and annotations of classes that are extended in `ShopBundle`

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Model/Product/Pricing/ProductPriceCalculationForUser.php
> +use Shopsys\FrameworkBundle\Model\Product\Product;
Please change `FrameworkBundle` to `ShopBundle` in usages and annotations of classes that are extended in `ShopBundle`

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Controller/Front/ProductController.php
> +            $productFilterData->minimalPrice /= ($this->currentCustomer->getCustomDiscount() ?? 100) / 100;
This does not work properly

2019-01-10 15:18 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Controller/Front/ProductController.php
> +            $productFilterData->maximalPrice /= ($this->currentCustomer->getCustomDiscount() ?? 100) / 100;
this does not work properly

2019-01-11 10:21 UTC, DavidOstrozlik requested changes
I have just one suggestion and it would be great if you added information to "admin - order detail - add product" that the added product will not have any individual discounts

2019-01-11 10:21 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Controller/Front/ProductController.php
> +            'discountCoeficient' => $this->currentCustomer->getDiscountCoeficient(),
This parameter is not used anywhere
```suggestion
```

2019-01-11 11:33 UTC, DavidOstrozlik approved these changes

2019-01-14 12:19 UTC, merged