Upgrade demoshop to version beta5
shopsys/demoshop pull request #33
Opened 2019-01-24 10:24 UTC by DavidOstrozlik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Keep demoshop upgraded with newest version of Framework
|New feature| No 
|BC breaks| No 
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-01-24 13:58 UTC, boris-brtan requested changes
Hi, THX for the upgrade, it could be in more commits but OK.
Please provide info in CHANGELOG.md let beta4 upgrade be your guide.

2019-01-24 15:16 UTC, boris-brtan commented
are we able somehow to mention ELASTIC_SEARCH_INDEX_PREFIX='' ???

2019-01-25 10:27 UTC, DavidOstrozlik commented
Hi, I added the info to CHANGELOG.md, but I don't think that ELASTIC_SEARCH_INDEX_PREFIX should be included there. I didn't do any changes related to it so I don't see the added value.

2019-01-25 10:45 UTC, boris-brtan requested changes
Quick fix and it will be OK

2019-01-25 10:45 UTC, boris-brtan commented on CHANGELOG.md
> +- [#27 - Upgrade to shopsys framework 7.0.0-beta5](https://github.com/shopsys/demoshop/pull/33)
```suggestion
- [#33 - Upgrade demoshop to version beta5](https://github.com/shopsys/demoshop/pull/33)
```

2019-01-25 11:16 UTC, boris-brtan approved these changes

2019-01-29 07:39 UTC, merged