upgrade to stable
shopsys/demoshop pull request #39
Opened 2019-03-01 19:46 UTC by boris-brtan

| Q             | A
| ------------- | ---
|Description, reason for the PR| to improve UPGRADE instructions and try the stable release with project that contains external changes 
|New feature| Yes 
|BC breaks| Yes 
|Fixes issues| many
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-03-04 11:38 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
> +msgstr "Firemní uživatelé"
```suggestion
msgstr "Uživatelé firmy"
```

2019-03-04 13:21 UTC, DavidOstrozlik requested changes
Hi, thanks for the PR. I found a few small things so check them out and I have one more question. Why didn't you change the implementation of picture element as it was the last upgrade instruction?

2019-03-04 13:21 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
> +msgstr "Firemní uživatelé"
```suggestion
msgstr "Uživatelé firmy"
```

2019-03-04 13:21 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
> +msgstr "Firma s vícero uživately"
```suggestion
msgstr "Firma s více uživateli"
```

2019-03-04 13:21 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
> +msgstr "Jeden nebo více e-mailů je duplikováno nebo se již používá, např.:"
```suggestion
msgstr "Jeden nebo více e-mailů je duplikován nebo se již používá, např.:"
```

2019-03-04 13:21 UTC, DavidOstrozlik commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
> +        /** @var \Shopsys\FrameworkBundle\Model\Product\ProductFacade $productFacade */
why did you change the annotation?

2019-03-04 13:21 UTC, DavidOstrozlik commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
> +        /** @var \Shopsys\FrameworkBundle\Model\Customer\CustomerFacade $customerFacade */
why did you change the annotation?

2019-03-04 13:21 UTC, DavidOstrozlik commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php
> +        $cartFacade = $this->getContainer()->get(CartFacade::class);
Why did you change this?

2019-03-04 13:21 UTC, DavidOstrozlik commented on tests/ShopBundle/Functional/Model/Pricing/InputPriceRecalculationSchedulerTest.php
> +        /** @var \Shopsys\ShopBundle\Model\Payment\Payment $payment */
there is no payment in shopbundle

2019-03-04 13:21 UTC, DavidOstrozlik commented on tests/ShopBundle/Functional/Model/Pricing/InputPriceRecalculationSchedulerTest.php
> +        /** @var \Shopsys\ShopBundle\Model\Payment\Payment $payment */
there is no payment in shopbundle

2019-03-04 13:31 UTC, boris-brtan commented on src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
> +msgstr "Firemní uživatelé"
fixup! translations from previous PRs are fixed

2019-03-04 14:05 UTC, boris-brtan commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
> +        /** @var \Shopsys\FrameworkBundle\Model\Product\ProductFacade $productFacade */
is is on project-base but also there is no ProductFacade on demoshop, so this was mistake in previous PRs

2019-03-04 14:08 UTC, boris-brtan commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
> +        /** @var \Shopsys\FrameworkBundle\Model\Customer\CustomerFacade $customerFacade */
based on UPGRADE instructions ....but i see it in demoshop so fix

2019-03-04 14:48 UTC, boris-brtan commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php
> +        $cartFacade = $this->getContainer()->get(CartFacade::class);
based on instuctions but i revert it back

2019-03-05 09:00 UTC, vitek-rostislav reviewed
Hi, the new changes look ok :+1: 

I briefly went through the whole PR and I have 2 more notes on that, please check them out :slightly_smiling_face:

2019-03-05 09:00 UTC, vitek-rostislav commented on migrations-lock.yml
> +20190215092226:
seems to me that these migrations should not be a part of this commit

2019-03-05 09:00 UTC, vitek-rostislav commented on CHANGELOG.md
> +    - services were created in Resources configs
what does this mean?

2019-03-05 09:05 UTC, vitek-rostislav commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php
> +        $cartFacade = $this->getContainer()->get(CartFacade::class);
what instruction was that?

2019-03-05 09:14 UTC, boris-brtan commented on migrations-lock.yml
> +20190215092226:
seems like after these changes build-demo-dev could get through the migrations, but OK i put it into the first commit

2019-03-05 09:26 UTC, boris-brtan commented on tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php
> +        $cartFacade = $this->getContainer()->get(CartFacade::class);
money, especially use the changed files based on commits

2019-03-05 09:27 UTC, boris-brtan commented on CHANGELOG.md
> +    - services were created in Resources configs
datafixture services were registrered in Resources/config/services/commands.yml and Resources/config/services/data_fixtures.yml

2019-03-05 09:48 UTC, vitek-rostislav approved these changes

2019-03-05 15:58 UTC, PetrHeinz commented
Beware that the `ProductController::applyDiscountForPriceFilter` now does nothing as the `Money` class is immutable. If in any doubt, check out the soon-to-be-released docs and upgrade notes for the `Money` class in https://github.com/shopsys/shopsys/pull/870

2019-03-06 07:33 UTC, DavidOstrozlik approved these changes

2019-03-15 10:46 UTC, merged