urls linked to Shopsys are fixed
shopsys/demoshop pull request #50
Opened 2019-05-30 10:40 UTC by boris-brtan

- shopsys-framework was integrated into shopsys
- http was changed into https

| Q             | A
| ------------- | ---
|Description, reason for the PR| shopsys-framework was joined with shopsys and secured hyper text transfer protocol sould be used.
|New feature| No 
|BC breaks| No 
|Fixes issues| 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-09-04 12:55 UTC, TomasLudvik approved these changes

2019-09-04 13:11 UTC, LukasHeinz requested changes
Travis CI check fails. Please fix it.

2019-09-05 09:41 UTC, TomasLudvik commented
> Travis CI check fails. Please fix it.

Fixed

2019-09-05 11:43 UTC, LukasHeinz approved these changes

2019-09-05 13:30 UTC, merged