Upgrade to version 7.3.0
shopsys/demoshop pull request #53
Opened 2019-07-11 21:51 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Upgrade demoshop to Shopsys Framework 7.3.0
|New feature| Yes 
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-07-12 10:29 UTC, vitek-rostislav reviewed
Hi, all the current changes seem ok to me, I have just extracted one change into a separate commit.

However, I am not able to build the application locally, it fails on error when running `product-search-create-structure`:
```
ERROR     [app] Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"no handler for type [icu_collation_keyword] declared on field [keyword]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: no handler for type [icu_collation_keyword] declared on field [keyword]","caused_by":{"type":"mapper_parsing_exception","reason":"no handler for type [icu_collation_keyword] declared on field [keyword]"}},"status":400} (uncaught exception) at /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php line 620 while running console command `shopsys:product-search:create-structure` ["exception" => Elasticsearch\Common\Exceptions\BadRequest400Exception { …}]
```

It is related to `icu_collation_keyword`, it works on CI, and I have a strong feeling it is caused by cached Docker images or something like that, so I am running a clean installation at the moment, I will let you know later whether it helped.

2019-07-12 12:02 UTC, vitek-rostislav commented
Hi, on my machine, the error is there even after the clean installation. Could you please confirm that it works on your local? Do you have any clue what am I missing? :confused:

2019-07-12 12:40 UTC, grossmannmartin commented
Hi, it reslky works on my machine, but I installed it locally. Can you take a look at docker container running Elasticsearch? If it’s created properly from dockerfile? I presume docker-compose file is valid.

2019-07-15 08:34 UTC, vitek-rostislav commented
Hi, everything works now, it seems like I have been using a wrong version of `docker-compose.yml`, my bad :man_facepalming:

2019-07-16 05:23 UTC, boris-brtan approved these changes

2019-07-16 05:40 UTC, boris-brtan requested changes
THX,
just one little thing

2019-07-16 05:40 UTC, boris-brtan commented on docker/conf/docker-compose.demo.yml.dist
> +            name: ${ELASTICSEARCH_NETWORK:-shared-demo-elasticsearch-icu-instance}
```suggestion
            name: ${ELASTICSEARCH_NETWORK:-shared-demo-elasticsearch-icu-network}
```

2019-07-16 05:43 UTC, boris-brtan approved these changes

2019-07-16 11:14 UTC, merged