Stop indexing pages
shopsys/demoshop pull request #64
Opened 2019-08-13 11:27 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| For demo we do not want to index pages by search engines
|New feature| No
|Fixes issues| ...
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-08-13 11:49 UTC, TomasLudvik requested changes
Hello @s3tezsky,

nice job here. I was thinking if it is ok to add "nofollow" because it was not part of the US, but it makes sense to me, you will just need to explain this to @LukasHeinz during BV. 

There are two small things I want to ask you: 
- in `src/Shopsys/ShopBundle/Resources/views/Front/Inline/Paginator/paginator.html.twig` is now unused macro `metaRobots` please remove this as well.
- squash those two commits with description like "disallow robots indexing of demoshop"

2019-08-13 11:49 UTC, TomasLudvik commented on src/Shopsys/ShopBundle/Resources/views/Front/Layout/base.html.twig
> +        <meta name="robots" content="noindex, nofollow">
Please add indentation here

2019-08-13 12:11 UTC, s3tezsky commented
I have fixed your comments @TomasLudvik 

```
A Noindex tag tells search engines that the relevant page should not be indexed in their search results. If you haven't added a Nofollow to the tag, however, search engines will still follow all the links on the page. In other words, the page will be read by search engines but it won't be indexed.
```

2019-08-13 13:45 UTC, TomasLudvik approved these changes
CR @ tested on http://ds-no-indexing.loki.shopsys.com. Good job!

2019-08-14 10:54 UTC, LukasHeinz approved these changes

2019-08-14 10:56 UTC, merged