Public demoshop update
shopsys/demoshop pull request #82
Opened 2019-09-06 10:06 UTC by TomasGottvald

| Q             | A
| ------------- | ---
|Description, reason for the PR| change blue to gold color, change contact person, add copyright image info, change footer text, remove unneded advert bottom gap, product list - bigger image, hide description
|New feature| No 
|Fixes issues| ...
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-09-06 13:02 UTC, LukasHeinz requested changes
It looks good.

But the change of color to gold is not done through all domains on 2. and 3. domain there is mixture of gold and green color. Either use green or gold. Not together.
![Snímek obrazovky 2019-09-06 v 14 59 50](https://user-images.githubusercontent.com/33071107/64429811-26334e80-d0b7-11e9-882b-bce9ac86a50a.png)

2019-09-09 06:05 UTC, TomasGottvald commented
I just resolved issues and made color changes for another domains.

2019-09-09 06:52 UTC, LukasHeinz approved these changes

2019-09-09 13:10 UTC, DavidOstrozlik requested changes
Hi. I added one suggestion please take a look at it.

2019-09-09 13:10 UTC, DavidOstrozlik commented on src/Shopsys/ShopBundle/Resources/views/Front/Layout/footer.html.twig
> +                {{ 'Powered by'|trans }} <a href="http://www.shopsys-framework.com/">Shopsys Framework</a>
Why should we use URL that is only http and redirects to the same place that the old one?

```suggestion
                {{ 'Powered by'|trans }} <a href="https://www.shopsys.com/">Shopsys Framework</a>
```

2019-09-09 15:44 UTC, TomasGottvald commented
> 
> 
> Hi. I added one suggestion please take a look at it.

Yes it makes sense. My update was according to Kamil´s notes.

2019-09-10 07:26 UTC, LukasHeinz requested changes
It is grat, only the FE user manu has have nicer dropdown - the curernt does not match any stly in FE and doesnt fit the menu.
![Snímek obrazovky 2019-09-10 v 9 24 21](https://user-images.githubusercontent.com/33071107/64592720-e917d680-d3ac-11e9-8791-13f95dd8e538.png)

2019-09-10 07:37 UTC, TomasGottvald commented
After discussion we agreed on these issues:
- cookie button - change color to gold
- active category color - change to gold
- change blue color on mobile menu
- change logged user menu - 13px font, 10px padding, remove hover background effect

2019-09-10 10:57 UTC, LukasHeinz submitted a review, later dismissed
On 2nd and 3rd domain there is still secondary color in category menu.
![Snímek obrazovky 2019-09-10 v 12 55 09](https://user-images.githubusercontent.com/33071107/64608272-8f260980-d3ca-11e9-8532-cacf93cd8e3d.png)
![Snímek obrazovky 2019-09-10 v 12 58 42](https://user-images.githubusercontent.com/33071107/64608365-c4325c00-d3ca-11e9-9483-f1f015c64319.png)

2019-09-17 08:18 UTC, TomasGottvald commented
@PetraPiprekova fixed #54 - fixed for german language.

2019-09-19 07:55 UTC, PetraPiprekova approved these changes
tests

2019-09-19 09:22 UTC, DavidOstrozlik approved these changes

2019-09-23 07:58 UTC, merged