Ds upgrade to dev master
shopsys/demoshop pull request #91
Opened 2019-11-27 16:48 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| Upgrade to 8.1
|New feature| No 
|Fixes issues| ...
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2019-12-02 09:35 UTC, DavidOstrozlik requested changes

2019-12-02 09:35 UTC, DavidOstrozlik commented on tests/ShopBundle/Acceptance/acceptance/VatInlineEditCest.php
> +class VatInlineEditCest
You didn't follow the whole upgrade instruction.. You should change the method as well not just the name of this class.

2019-12-02 15:45 UTC, DavidOstrozlik approved these changes
Looks OK by me. Just don't forget about translations on BV.

2019-12-04 09:26 UTC, DavidOstrozlik approved these changes

2019-12-04 09:53 UTC, sslt approved these changes

2019-12-04 10:02 UTC, merged